name: Build & Deploy

on: 
  push:
    branches:
      - main
      
env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3️⃣ Install dependencies (in React subfolder)
      - name: Install dependencies
        run: npm install
        working-directory: React-project

      # 4️⃣ Build the React app
      - name: Build Project
        run: npm run build
        working-directory: React-project

      # 5️⃣ Upload production-ready build files
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: React-project/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # 6️⃣ Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: React-project/build

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: React-project/build
