name: Build & Deploy

on: 
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js (Vite requires Node 20+)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3️⃣ Install dependencies inside vite-project
      - name: Install dependencies
        run: |
          cd vite-project
          npm install

      # 4️⃣ Build the Vite app
      - name: Build Project
        run: |
          cd vite-project
          npm run build

      # 5️⃣ Upload production-ready build files (dist folder for Vite)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: vite-project/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # 6️⃣ Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: vite-project/dist

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: vite-project/dist
